services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    volumes:
      - ./mongodb:/data/db
    ports:
      - "27017:27017"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env.docker
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "5173:5173"
    depends_on:
      - server
    env_file:
    - ./client/.env.docker
